# A Dictionary of every phrase in the program ofr every supported language

deutsch = {
    # Main menu
    'welcome_screen': "Wilkommen bei SCHIFFEVERSENKEN-2021",
    'bye': "Auf Wiedersehen!", 'invalid_input': "Die Eingabe ist keine gültige Option.",
    'start_game': "Spiel starten",
    'quit': "Spiel verlassen",
    'really_leave': "Wollen Sie wirklich das Spiel verlassen?",
    'really_leave_error': "Ungültige eingabe. Tippen Sie y für Ja oder n für nein",

    # Settings menu
    'settings': 'Einstellungen',
    'choose_board_size': 'Wählen Sie eine möglich Spielfeldgröße aus',
    'change_board_size': "Spielfeldgröße ändern",
    'change_ship_amount': "Schiffanzahl ändern",
    'change_language': "Sprache ändern",
    'choose_language': "Wählen Sie Ihre Sprache",
    'toggle_countdown': "Zeitlimit beim Spielen an und ausschalten",
    'toggle_countdown_default_on': "Wollen Sie ein Zeitlimit bei jedem Spielzug [Standart : An]",
    'countdown_on': "Ja",
    'countdown_off': "Nein",
    'change_bot_difficulty': "Schwierigkeitsgrad vom pve Spiel ändern",
    'choose_bot_level': "Wählen Sie ein Schwierigkeitsgrad für das pve Spiel",
    'easy': "Einfach",
    'normal': "Mittel",
    'hard': "Schwer",
    'how_many_ships': "Wie viele Schiffe wollen Sie platzieren",
    'how_many_ships_error': "Sie müssen mindestens 3 und maximal 10 Schiffe platzieren",

    # General phrases
    'back': "Zurück",
    'press_enter_to_continue': "Drücke die Eingabetaste um fortzufahren",
    'your_choice': "Ihre Wahl",
    'what_to_do': "Was wollen Sie tun",

    # Start of game and naming
    'type_of_game': "Wählen Sie die gewünschte Spielart",
    'pve': "Player vs Bot",
    'pvp': "Player vs Player",
    'name_first_player': "Wie soll der erste Spieler heißen",
    'name_human_player': "Wie wollen Sie sich nennen",
    'name_second_player': "Wie soll der zweite Spieler heißen",
    'name_player_error': "Der Name darf nicht Leer sein, und darf max 12 Zeichen haben",
    'name_is_taken': "Dieser Name ist schon belegt. Wählen Sie einen anderen Namen",
    'human_v_human': "Mensch gegen Mensch",
    'human_v_machine': "Mensch gegen Maschine",
    'welcome': "Willkommen",
    'and': "und",
    'start_the_fight': "Möge die Schlacht beginnen",
    'you_are_playing_against': "Sie spielen heute gegen",

    # In-game phrases
    'press_enter_when': "Drücken Sie ENTER wenn",
    'is_at_the_screen': "am Computer ist",
    'has_won_the_game': "hat gewonnen!",
    'enter_to_go_back': "Drücke Enter um zurück zum Hauptmenu zu kommen",
    'is_playing': "ist dran",
    'you_are_playing': "Sie sind dran",
    'what_is_your_next_play': "Was ist Ihr nächster Zug",
    'you_ve_already_shot_there': "Sie haben schon auf dieses Feld geschossen",
    'switch_places_and_press_enter_when': "Tauschen Sie die Plätze und drücken Sie Enter wenn",
    'is_not_looking': "nicht mehr schaut",
    'you_ve_hit_an_enemy': "Sie haben ein gegnerisches Schiffe getroffen!",
    'you_ve_destroyed': "Sie haben das gegnerische",
    'sunk': "versenkt",
    'miss_phrases': ["Daneben", "Ein Schuss ins Wasser", "Nicht getroffen", "Du Dödel. Voll verfehlt"],
    'hit_phrases': ["Volltreffer", "Hit", "Yippee-ki-yay M*****F*****"],
    'shot_into_water': "hat ins Wasser geschossen auf",
    'hit_your': "hat Ihren",
    'hit_your_2': "getroffen",
    'destroyed_your': "hat Ihren",
    'your_time': "Ihre Zeit",
    'times_up': "Zeit ist abgelaufen",
    'times_up_random_shot': "Ihre Zeit ist abgelaufen. Es wurde ein zufälliges Feld beschossen",

    # Ship names
    'patrol_boat': "Patrouillenboot",
    'submarine': "U-Boot",
    'destroyer': "Zerstörer",
    'battleship': "Schlachtschiff",
    'carrier': "Flugzeugträger",

    # Ship placement and board printing
    'placed_their_ships': "hat seine Schiffe gesetzt",
    'place_ships_yourself': "Schiffe selber platzieren",
    'place_ships_randomly': "Schiffe zufällig auf dem Feld verteilen",
    'your': "Ihr",
    'is': "ist",
    'field_big_where_to_start': "Felder groß. Wo soll die Spitze liegen",
    'not_enough_space_for': "An dieser Stelle ist nicht genug Platz für Ihren",
    'the_front_is_on': "Die Spitze ist bei",
    'where_to_put_the_back__your_choices': "Wo soll das Ende des Schiffes liegen? Möglichkeiten sind",
    'your_board': "Ihr Spielfeld",
    'your_enemys_board': "Das Spielfeld des Gegners",
    'how_many_ships_left': "Anzahl an lebenden Schiffen: "
}

english = {
    # Main menu
    'welcome_screen': "Welcome to BATTLESHIP-2021",
    'bye': "Goodbye!",
    'invalid_input': "This input is not a valid option.",
    'start_game': "Start game",
    'quit': "Leave game",
    'really_leave': "Do you really want to leave the game?",
    'really_leave_error': "Invalid input. Type y for yes or n for no",

    # Settings menu
    'settings': 'Settings',
    'choose_board_size': 'Choose one of the available board size option',
    'change_board_size': "Change the size of the board",
    'change_ship_amount': "Change the number of ships",
    'change_language': "Change the language",
    'choose_language': "Choose your language",
    'toggle_countdown': "Toggle time limit for each turn",
    'toggle_countdown_default_on': "Do you want a time limit for each turn? [Default : On]",
    'countdown_on': "Yes",
    'countdown_off': "No",
    'change_bot_difficulty': "Change difficulty level of the pve game",
    'choose_bot_level': "Choose a difficulty level for the pve game",
    'easy': "Easy",
    'normal': "Normal",
    'hard': "Hard",
    'how_many_ships': "How many ships do you want to play with",
    'how_many_ships_error': "You need at least 3 ship and at most 10",

    # General phrases
    'back': "Go back",
    'press_enter_to_continue': "Press Enter to continue",
    'your_choice': "What do you want to do",
    'what_to_do': "What do you want to do",

    # Start of game and naming
    'type_of_game': "Want type of game do you want to play",
    'pve': "Player vs Bot",
    'pvp': "Player vs Player",
    'name_first_player': "How should the first player be called",
    'name_human_player': "How do you want to be called",
    'name_second_player': "How should the second player be called",
    'name_player_error': "The name can't be empty, and can be at most 12 characters long",
    'name_is_taken': "This name is already taken. Choose another name",
    'human_v_human': "Human against Human",
    'human_v_machine': "Human against the Machine",
    'welcome': "Welcome",
    'and': "and",
    'start_the_fight': "Let the battle begin",
    'you_are_playing_against': "You are playing against",

    # In-game phrases
    'press_enter_when': "Press ENTER when",
    'is_at_the_screen': "is at the computer",
    'has_won_the_game': "has won the game!",
    'enter_to_go_back': "Press Enter to go back to the main menu",
    'is_playing': "is playing",
    'you_are_playing': "it is your turn",
    'what_is_your_next_play': "What is your next play",
    'you_ve_already_shot_there': "You've already shot there",
    'switch_places_and_press_enter_when': "Switch places and press Enter when",
    'is_not_looking': "isn't looking anymore",
    'you_ve_hit_an_enemy': "You've hit the enemy's ",
    'you_ve_destroyed': "You've destroyed the enemy's ",
    'sunk': "",
    'miss_phrases': ["Daneben", "Ein Schuss ins Wasser", "Nicht getroffen", "Du Dödel. Voll verfehlt"],
    'hit_phrases': ["Volltreffer", "Hit", "Yippee-ki-yay M*****F*****"],
    'shot_into_water': "shot into the water on",
    'hit_your': "hit your",
    'hit_your_2': "",
    'destroyed_your': "destoyed your",
    'your_time': "Your time",
    'times_up': "Time's up",
    'times_up_random_shot': "Your time is up, a random field was chosen",

    # Ship names
    'patrol_boat': "patrol boat",
    'submarine': "submarine",
    'destroyer': "destroyer",
    'battleship': "battleship",
    'carrier': "carrier",

    # Ship placement and board printing
    'placed_their_ships': "placed its ships",
    'place_ships_yourself': "Place the ships yourself",
    'place_ships_randomly': "Place ships randomly on the board",
    'your': "Your",
    'is': "is",
    'field_big_where_to_start': "spaces long. Where should the front be placed",
    'not_enough_space_for': "There is not enough space there for your",
    'the_front_is_on': "The front will be placed on",
    'where_to_put_the_back__your_choices': "Where should the back be placed. Your choices are",
    'your_board': "Your board",
    'your_enemys_board': "The enemy's board",
    'how_many_ships_left': "Number of living ships: "
}

francais = {
    # Main menu
    'welcome_screen': "Bienvenue sur BATAILLE-NAVALE-2021",
    'bye': "Au revoir!",
    'invalid_input': "Ceci n'est pas une option valable",
    'start_game': "Commencer une partie",
    'quit': "Quitter le jeu",
    'really_leave': "Voulez vous vraiment quitter le jeu?",
    'really_leave_error': "Option invalide. Entrez y pour oui ou n pour non",

    # Settings menu
    'settings': 'Paramètres',
    'choose_board_size': "Choisissez une taille de plateau de jeu",
    'change_board_size': "Changer la taille du plateau de jeu",
    'change_ship_amount': "Changer le nombre de bateaux par joueur",
    'change_language': "Changer la langue",
    'choose_language': "Choisissez votre langue",
    'toggle_countdown': "Activer ou désactiver la limite de temps pour chaque tour",
    'toggle_countdown_default_on': "Voulez-vous une limit de temps pour chaque tour [Standard : On]",
    'countdown_on': "Oui",
    'countdown_off': "Non",
    'change_bot_difficulty': "Changer le niveau de difficulté du jeu pve",
    'choose_bot_level': "Choisissez un niveau de difficulté pour le jeu contre ordinateur",
    'easy': "Facile",
    'normal': "Normal",
    'hard': "Difficile",
    'how_many_ships': "Combien de bateaux voulez-vous par joueur",
    'how_many_ships_error': "Vous devez choisir entre 3 et 10 bateaux par joueur",

    # General phrases
    'back': "Retour",
    'press_enter_to_continue': "Appuyez sur la touche ENTER pour continuer",
    'your_choice': "Que voulez-vous faire",
    'what_to_do': "Que voulez-vous faire",

    # Start of game and naming
    'type_of_game': "Quelle type de partie voulez jouer",
    'pve': "Joueur vs ordinateur",
    'pvp': "Joueur vs joueur",
    'name_first_player': "Comment s'appelle le premier joueur",
    'name_human_player': "Comment voulez-vous vous appeler",
    'name_second_player': "Comment s'appelle le deuxième joueur",
    'name_player_error': "Le nom ne peux pas être vide ou plus long que 12 charactères",
    'name_is_taken': "Ce nom est déjà pris. Choisissez un autre nom.",
    'human_v_human': "Humain contre humain",
    'human_v_machine': "Humain contre Machine",
    'welcome': "Bienvenue",
    'and': "et",
    'start_the_fight': "Que la bataille commence",
    'you_are_playing_against': "Vous jouez aujourd'hui contre",

    # In-game phrases
    'press_enter_when': "Appuyer la touche ENTER dès que",
    'is_at_the_screen': "est à l'écran",
    'has_won_the_game': "a gagné!",
    'enter_to_go_back': "Appuyer la touche ENTER pour retourner au menu principal",
    'is_playing': ", c'est a votre tour",
    'you_are_playing': "c'est votre a votre tour",
    'what_is_your_next_play': "Où voulez-vous tirer",
    'you_ve_already_shot_there': "Vous avez déjà tiré sur cette case",
    'switch_places_and_press_enter_when': "Échangez vos places et appuyez la touche ENTER dès que",
    'is_not_looking': "n'est plus à l'écran",
    'you_ve_hit_an_enemy': "Vous avez touché un bateau ennemie!",
    'you_ve_destroyed': "Vous avez coulez le ",
    'sunk': "ennemie",
    'miss_phrases': ["A coté", "Un tir dans l'eau", "Raté"],
    'hit_phrases': ["En plein dans le mille", "Touché", "Yippee-ki-yay M*****F*****"],
    'shot_into_water': "a tirer dans l'eau sur",
    'hit_your': "a touché votre",
    'hit_your_2': "",
    'destroyed_your': "a coulé votre",
    'your_time': "Votre temps",
    'times_up': "Votre temps est écoulé",
    'times_up_random_shot': "Votre temps est écoulé. Une case a été choisi au hasard.",

    # Ship names
    'patrol_boat': "torpilleur",
    'submarine': "sous-marin",
    'destroyer': "contre-Torpilleur",
    'battleship': "cuirassé",
    'carrier': "porte-avion",

    # Ship placement and board printing
    'placed_their_ships': "a placé ses bateaux",
    'place_ships_yourself': "Placer les bateaux vous même",
    'place_ships_randomly': "Placer les bateaux au hasard",
    'your': "Votre",
    'is': "a besoin de",
    'field_big_where_to_start': "cases. Sur quelle case voulez-vous placer l'avant",
    'not_enough_space_for': "Il n'y a pas assez de place sur cette case pour votre",
    'the_front_is_on': "L'avant est sur la case",
    'where_to_put_the_back__your_choices': "Sur quelle case voulez vous placer l'arrière. Les possibilitées sont ",
    'your_board': "Votre terrain",
    'your_enemys_board': "Le terrain ennemi",
    'how_many_ships_left': "Nombre de bateaux vivants: "
}
