deutsch = {"welcome_screen": "Wilkommen bei SCHIFFEVERSENKEN-2021",
           "your_choice": "Ihre Wahl",
           "bye": "Auf Wiedersehen!",

           "invalid_input": "Die Eingabe ist keine gültige Option.",
           "what_to_do": "Was wollen Sie tun",
           "start_game": "Spiel starten",
           'quit': "Spiel verlassen",
           'really_leave': "Wollen Sie wirklich das Spiel verlassen?",
           'really_leave_error': "Ungültige eingabe. Tippen Sie y für Ja oder n für nein",

           "settings": 'Einstellungen',
           'choose_board_size': 'Wählen Sie eine möglich Spielfeldgröße aus',
           'change_board_size': "Spielfeldgröße ändern",
           'change_ship_amount': "Schiffanzahl ändern",
           'change_language': "Sprache ändern",
           'choose_language': "Wählen Sie Ihre Sprache",
           'how_may_ships': "Wie viele Schiffe wollen Sie platzieren",
           'how_many_ships_error': "Sie müssen mindestens 3 und maximal 10 Schiffe platzieren",

           'back': "Zurück",
           'press_enter_to_continue': "Drücke die Eingabetaste um fortzufahren",

           'type_of_game': "Wählen Sie die gewünschte Spielart",
           'pve': "Player vs Bot",
           'pvp': "Player vs Player",
           'name_first_player': "Wie soll der erste Spieler heißen",
           'name_second_player': "Wie soll der zweite Spieler heißen",
           'name_player_error': "Der Name darf nicht Leer sein, und darf max 12 Zeichen haben",
           'name_is_taken': "Dieser Name ist schon belegt. Wählen Sie einen anderen Namen",

           'human_v_human': "Mensch gegen Mensch",
           'welcome': "Willkommen",
           'and': "und",
           'start_the_fight': "Möge die Schlacht beginnen",
           'is_playing_look_away': "ist dran. Drücken Sie ENTER wenn nur noch",
           'is_at_the_screen': "am Computer ist",
           'has_won_the_game': "hat gewonnen!",
           'enter_to_go_back': "Drücke Enter um zurück zum Hauptmenu zu kommen",
           'is_playing': "ist dran",
           'what_is_your_next_play': "Was ist Ihr nächster Zug",
           'you_ve_already_shot_there': "Sie haben schon auf dieses Feld geschossen",
           'switch_places_and_press_enter_when': "Tauschen Sie die Plätze und drücken Sie Enter wenn",
           'isnt_looking': "nicht mehr schaut",
           'you_ve_hit_an_enemy': "Sie haben ein gegnerisches Schiffe getroffen!",
           'you_ve_destroyed': "Sie haben das gegnerische",
           "sunk": "versenkt",

           'patrol_boat': "Patrouillenboot",
           'submarine': "U-Boot",
           'destroyer': "Zerstörer",
           'battleship': "Schlachtschiff",
           'carrier': "Flugzeugträger",

           'place_ships_yourself': "Schiffe selber platzieren",
           'place_ships_randomly': "Schiffe zufällig auf dem Feld verteilen",
           'your': "Dein",
           'is': "ist",
           "field_big_where_to_start": "Felder groß. Wo soll die Spitze liegen",
           'not_enough_space_for': "An dieser Stelle ist nicht genug Platz für dein",
           'the_front_is_on': "Die Spitze ist bei",
           'where_to_put_the_back__your_choices': "Wo soll das Ende des Schiffes liegen? Möglichkeiten sind",
           'your_board': "Ihr Spielfeld",
           'your_enemys_board': "Das Spielfeld des Gegners",
           'how_many_ships_left': "Anzahl an lebenden Schiffen: "

           }

english = {"welcome_screen": "Welcome to BATTLESHIP-2021",
           "your_choice": "What do you want to do",
           "bye": "Goodbye!",

           "invalid_input": "This input is not a valid option.",
           "what_to_do": "What do you want to do",
           "start_game": "Start game",
           'quit': "Leave game",
           'really_leave': "Do you really want to leave the game?",
           'really_leave_error': "Invalid input. Type y for yes or n for no",

           "settings": 'Settings',
           'choose_board_size': 'Choose one of the available board size option',
           'change_board_size': "Change the size of the board",
           'change_ship_amount': "Change the number of Ships",
           'change_language': "Change the Language",
           'choose_language': "Choose your language",
           'how_many_ships': "How many ships do you want to play with",
           'how_many_ships_error': "You need at least 3ship and at most 10",

           'back': "Go back",
           'press_enter_to_continue': "Press Enter to continue",

           'type_of_game': "Want type of game do you want to play",
           'pve': "Player vs Bot",
           'pvp': "Player vs Player",
           'name_first_player': "How should the first Player be called",
           'name_second_player': "How should the second Player be called",
           'name_player_error': "The name can't be empty, and can be at most 12 characters long",
           'name_is_taken': "This name is already taken. Choose another name",

           'human_v_human': "Human versus Human",
           'welcome': "Welcome",
           'and': "and",
           'start_the_fight': "Let the battle begin",
           'is_playing_look_away': "is now playing. Press Enter when only",
           'is_at_the_screen': "is at the computer",
           'has_won_the_game': "has won the game!",
           'enter_to_go_back': "Press Enter to go back to the main menu",
           'is_playing': "is playing",
           'what_is_your_next_play': "What is your next play",
           'you_ve_already_shot_there': "You've already shot there",
           'switch_places_and_press_enter_when': "Switch places and press Enter when",
           'isnt_looking': "isn't looking anymore",
           'you_ve_hit_an_enemy': "You've hit the enemy's !",
           'you_ve_destroyed': "You've destroyed the enemy's ",
           "sunk": "",

           'patrol_boat': "patrol boat",
           'submarine': "submarine",
           'destroyer': "destroyer",
           'battleship': "battleship",
           'carrier': "carrier",

           'place_ships_yourself': "Place the ships yourself",
           'place_ships_randomly': "Place ships randomly on the board",
           'your': "Your",
           'is': "is",
           "field_big_where_to_start": "spaces long. Where should the front be placed",
           'not_enough_space_for': "There is not enough space there for your",
           'the_front_is_on': "The front is located on",
           'where_to_put_the_back__your_choices': "Where should the back be placed. Your choices are",
           'your_board': "Your board",
           'your_enemys_board': "The enemy's board",
           'how_many_ships_left': "Number of living ships: "

           }
